### ISSUE TITLE
Delete Contact Text Field from Disaster Relief Sample Survey

### ISSUE THREAD

**Issue by eehjunggnujhee** [SFDO-Community/GrassrootsMobileSurveyApp#100]
The `Contact Text` field label wasn’t clear. I put a string like above and got a nice error message.
Remove Contact Text
Add checkbox under Phone Number  - “can receive texts at this number” or similar

- Delete Contact_Text__c from Field Surveys object
- Created a new field labeled, `Accept Consent to Receive SMS Text Mssg`  (SMSConsent__c)
- Add the new field to the Disaster Relief Page layout and GRMS_App_Sample_Survey.permissionset

How to validate: spin up a scratch org, run the command `sfdx force:source:push`, and confirm the changes

**Comment by eehjunggnujhee** [comment]
PR: https://github.com/SFDO-Community-Sprints/GrassrootsSurveySalesforcePackage/pull/16 @kdveverka @shunkosa

**Comment by kdveverka** [comment]
Verified this one is done in the current version and can be closed.
