### ISSUE TITLE
Unclear Paragraph In Install Instructions

### ISSUE THREAD

**Issue by mkolodner** [SFDO-Community/GrassrootsMobileSurveyApp#103]
I completely don't understand the second sentence of this paragraph:
"5. Move the field to a place on the page layout that is appropriate for your use case. On the next page, specify the related list that will use the Field Worker and Client Layout AND the Contact Layout (for contacts that are neither Field Workers nor Survey Clients.) Click on Save."

**Comment by kdveverka** [comment]
Fixed.
