### ISSUE TITLE
Recommended Edit

### ISSUE THREAD

**Issue by mkolodner** [SFDO-Community/GrassrootsMobileSurveyApp#104]
In the paragraph below, recommend adding the text in bold
"Create a Record Type

Most organizations need several surveys for **use in** the field, for example, New Client, Health Visit, Paperwork Visit, Student Success Visit, etc. For each distinct kind of survey that will have its own fields and picklists and will need its own page layout, create a record type. If you are using the Sample Survey pack, it comes with two record types - Disaster Relief and Homecare. (Pro Tip: Keep Homecare and Disaster Relief Survey record types **in your org** to modify to meet your needs, if they will be useful for you.)"

**Comment by kdveverka** [comment]
Complete
