### ISSUE TITLE
Recommended Edit - Compact Layouts

### ISSUE THREAD

**Issue by mkolodner** [SFDO-Community/GrassrootsMobileSurveyApp#105]
Need to edit the paragraph that begins "Adjust the Field Survey's Compact Layout..."

Things to add:
1. The field that is at the top of a Compact Layout for a record type will be the field that shows in the list of available surveys in the mobile app. [a screenshot of the mobile app would be helpful here!]
2. The example field to remove from the compact layout is "First Gift Date." But that's a Contact field, not one on Field Survey. The default compact layout for Field Survey, in fact, only has Survey Number in it, so there is no need to remove, only to add and perhaps change what should be the top field.

**Comment by kdveverka** [comment]
Complete
