### ISSUE TITLE
"Assign Field Survey Record Types to Profiles" needs a paragraph number. Move up?

### ISSUE THREAD

**Issue by mkolodner** [SFDO-Community/GrassrootsMobileSurveyApp#106]
The instructions for assigning Field Survey record types to profiles (paragraph begins "Assign Field Survey Record Types to Profiles") should probably be numbered 6 because it's not part of #5, assigning compact layouts.

I would also argue that assigning record types to profiles should probably go higher up in the instructions -- probably just after "Create a Record Type."

**Comment by kdveverka** [comment]
Rethinbking the order on this bit. Need to do a quick outline and think about the best logical order.

**Comment by kdveverka** [comment]
Overhauled the "Configure Custom Objects, Record Types, Layouts, and Custom Fields" section.
