### ISSUE TITLE
"Create a Record Type" not needed if the Sample Survey Package is installed

### ISSUE THREAD

**Issue by mkolodner** [SFDO-Community/GrassrootsMobileSurveyApp#107]
Add a note in this section that if you have installed the Sample Survey Package you will already have two record types installed (so no need to create one) but that those record types are not assigned to any profiles.

**Comment by kdveverka** [comment]
Noting to assign these to profiles. the callout that you have two record types already if you have the sample pack is already there (may have been added after you put this issue in).
