### ISSUE TITLE
Cannot read property "replace" of null

### ISSUE THREAD

**Issue by karenfitton** [SFDO-Community/GrassrootsMobileSurveyApp#108]
Using the sample disaster survey with only appetite and survey client on the survey - when I create surveys and then sync I get the message Cannot read property 'replace' of null.  The survey does show up in Salesforce but the mobile app does not look like the survey synced.

If I logout and log back into the app, it does show that the survey was synced. 

This is happening on every sync

**Comment by kdveverka** [comment]
@shunkosa - Two other users got this, both using the sample survey pack. Testing w/out it, I've been unable to replicate. Let me know what I can do to assist w/narrowing it down.

**Comment by kdveverka** [comment]
@shunkosa - Any progress on this one?

**Comment by shunkosa** [comment]
@karenfitton @kdveverka I still cannot repro this issue but I modified the code block which potentially causes this error. Can you try v0.9.1 and see if the error still happens? Let me know if you need the android version

**Comment by kdveverka** [comment]
@shunkosa - The good news is I cannot reproduce it on Android or IOS with a fresh install. Trish will be testing today too.

**Comment by kdveverka** [comment]
@shunkosa - Trish just got this error on Android mobile client.

**Comment by kdveverka** [comment]
@shunkosa - We've narrowed this to what seems to be the survey client lookup field. That is the commonality. Trish was able to get this error again today.

**Comment by eehjunggnujhee** [comment]
hi @shunkosa 
Would it be possible that the code is setting empty value to the lookup field here that is causing the error?

src/components/surveyEditor/Lookup.tsx

function Lookup({ fieldName, fieldLabel, title, value, navigation, disabled }: LookupPropType) {
  const [lookupToName, setLookupToName] = useState('');
  
  It looks like the useState seems to be setting the initial value of the lookup field kind to blank which will cause an error for the lookup field. Let me know

**Comment by kdveverka** [comment]
@shunkosa - Have you had a chance to look at Jung's idea above?

**Comment by shunkosa** [comment]
Ill look into it soon!

**Comment by shunkosa** [comment]
Fixed version is available in TestFligh now.
[grassroots_v0.10.1.apk.zip](https://github.com/SFDO-Community/GrassrootsMobileSurveyApp/files/11974782/grassroots_v0.10.1.apk.zip)
