### ISSUE TITLE
Remove duplicative permission set from Sample Survey Pack

### ISSUE THREAD

**Issue by kdveverka** [SFDO-Community/GrassrootsMobileSurveyApp#113]
The permission set Grassroots Survey App Sample Survey is a duplicate of the Grassroots Survey App Admin permission set. It is confusing to have both in there. The next version of the Sample Survey pack should remove it.

**Comment by shunkosa** [comment]
Will be removed in https://github.com/SFDO-Community/GrassrootsSurveySalesforcePackage/pull/25

**Comment by kdveverka** [comment]
@shunkosa - My mistake- this had the record type perms for the sample packge but was poorly named. We've opened Issue #117 for this.
