### ISSUE TITLE
Sample Survey Package still in Beta

### ISSUE THREAD

**Issue by kdveverka** [SFDO-Community/GrassrootsMobileSurveyApp#114]
Sample Survey pack still a beta and cannot be installed in production orgs. This was going to go on MetaDeploy but I think that never happened. Screen shot below when I tried it in a production instance. 

![Screen Shot 2022-12-10 at 1 17 57 PM](https://user-images.githubusercontent.com/44512446/206869641-c489abb5-20da-4ff0-8be4-c6786fe1f3df.png)

I am using the link we have on the [Salesforce Initial Setup page.](https://github.com/SFDO-Community/GrassrootsMobileSurveyApp/wiki/Salesforce-Initial-Setup)

**Comment by shunkosa** [comment]
Working in https://github.com/SFDO-Community/GrassrootsSurveySalesforcePackage/pull/25. We should change `cumulusci.yaml` and need support and review from SFDO eng. team.

**Comment by coriobriensfdo** [comment]
@shunkosa what support do you need? Feel free to send a Slack message and I can help.

**Comment by shunkosa** [comment]
@coriobriensfdo check out the above PR. Review by eng teem is required when we modify cumulus ci settings.

**Comment by kdveverka** [comment]
@shunkosa - Do we still need eng team assistance here?

**Comment by kdveverka** [comment]
@shunkosa - I installed .3.0.1 and still no sample survey package. I'm not seeing a new link for just the sample surveys that is newer than the beta that doesn't allow install in Prod. Is there one.

**Comment by shunkosa** [comment]
https://install.salesforce.org/products/grms/latest should be updated and I'm waiting for it
