### ISSUE TITLE
Unable to login on newest Mobile Clients - iOS v0.12.0 & Android Beta 0.12.0

### ISSUE THREAD

**Issue by kdveverka** [SFDO-Community/GrassrootsMobileSurveyApp#129]
The latest mobile clients error out on login. They get to the username and password, attempt to load Contact records and fail. The error is not specific - it just says Error. Verified it's not a username and pw issue by using Android v 0.9.0 and the same username and pw w/no problems.

**Comment by kdveverka** [comment]
@shunkosa - I have this on a mobile client and can show you when you have time

**Comment by shunkosa** [comment]
@kdveverka Can I have details? Error message, device, etc...

**Comment by kdveverka** [comment]
@shunkosa - Can't reproduce so far on 0.12.1 so the issue may be gone. I'll close.

**Comment by kdveverka** [comment]
@shunkosa - This is potentially back. The client just displays an Error with no message after getting partway through the login. I can see in Auth0 that the user is successfully authenticated and in SF that the user config'd in Heroku is successfully authenticated so I'm getting something is not going right on the confirmation back to Heroku or the final token handoff to the mobile client. I'm using the latest mobile client and Heroku stack v22.
